import { TubeSample } from "../lib/types";

export const sampleData: TubeSample[] = [
  {
    name: "Alice Johnson",
    id: 1,
    age: 34,
    workPlace: "Hospital",
    district: "Central",
    visionDefects: "Myopia",
    rack: undefined,
  },
  {
    name: "Bob Smith",
    id: 2,
    age: 42,
    workPlace: "School",
    district: "North",
    visionDefects: "Hyperopia",
    rack: undefined,
  },
  {
    name: "Cathy Lee",
    id: 3,
    age: 28,
    workPlace: "Tech Company",
    district: "East",
    visionDefects: "Astigmatism",
    rack: undefined,
  },
  {
    name: "David Brown",
    id: 4,
    age: 51,
    workPlace: "Bank",
    district: "South",
    visionDefects: "Presbyopia",
    rack: undefined,
  },
  {
    name: "Emma Davis",
    id: 5,
    age: 37,
    workPlace: "Restaurant",
    district: "West",
    visionDefects: "Myopia",
    rack: undefined,
  },
  {
    name: "Frank Wilson",
    id: 6,
    age: 45,
    workPlace: "Library",
    district: "Central",
    visionDefects: "Glaucoma",
    rack: undefined,
  },
  {
    name: "Grace Taylor",
    id: 7,
    age: 30,
    workPlace: "Clinic",
    district: "North",
    visionDefects: "Astigmatism",
    rack: undefined,
  },
  {
    name: "Henry Martinez",
    id: 8,
    age: 39,
    workPlace: "Construction Site",
    district: "South",
    visionDefects: "Hyperopia",
    rack: undefined,
  },
  {
    name: "Ivy Garcia",
    id: 9,
    age: 29,
    workPlace: "University",
    district: "East",
    visionDefects: "Myopia",
    rack: undefined,
  },
  {
    name: "Jack White",
    id: 10,
    age: 56,
    workPlace: "Government Office",
    district: "West",
    visionDefects: "Cataracts",
    rack: undefined,
  },
];
